version: 0.2.{build}
configuration:
- Debug
- Release
platform: x86
clone_folder: C:\Projects\DeltaEngine\
build:
  project: DeltaEngine.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - marc.izquierdo.hu@gmail.com
  subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
  message: >-
    <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
        {{#passed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#078DC7;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} completed</a></h1>{{/passed}}
        {{#failed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
        <p style="color: #888;">
            Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
            <br />
            <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
        </p>
        <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
    </div>
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true