#pragma once

#define DELTAENGINE_LOG_LEVEL_FATAL 0
#define DELTAENGINE_LOG_LEVEL_ERROR 1
#define DELTAENGINE_LOG_LEVEL_WARN  2
#define DELTAENGINE_LOG_LEVEL_INFO  3
#define DELTAENGINE_LOG_LEVEL_DEBUG	4