#pragma once

#ifndef __DELTAENGINE_ERRORS__
#define __DELTAENGINE_ERRORS__

#define ERR_GLFW_INIT			1
#define ERR_GLFW_CREATE_WINDOW	2

#define ERR_CREATING_FILE		3

#define ERR_EXPECTED_ARGUMENT	4
#define ERR_INVALID_ARGUMENT	5
#endif